class TkPatterns {
  static const tkLocaleDatePatterns = {
    'd': 'd.',
    'E': 'ccc',
    'EEEE': 'cccc',
    'LLL': 'LLL',
    'LLLL': 'LLLL',
    'M': 'L.',
    'Md': 'd.M.',
    'MEd': 'EEE d.M.',
    'MMM': 'LLL',
    'MMMd': 'd. MMM',
    'MMMEd': 'EEE d. MMM',
    'MMMM': 'LLLL',
    'MMMMd': 'd. MMMM',
    'MMMMEEEEd': 'EEEE d. MMMM',
    'QQQ': 'QQQ',
    'QQQQ': 'QQQQ',
    'y': 'y',
    'yM': 'M.y',
    'yMd': 'd.M.y',
    'yMEd': 'EEE d.MM.y',
    'yMMM': 'MMM y',
    'yMMMd': 'd. MMM y',
    'yMMMEd': 'EEE d. MMM y',
    'yMMMM': 'MMMM y',
    'yMMMMd': 'd. MMMM y',
    'yMMMMEEEEd': 'EEEE d. MMMM y',
    'yQQQ': 'QQQ y',
    'yQQQQ': 'QQQQ y',
    'H': 'HH',
    'Hm': 'HH:mm',
    'Hms': 'HH:mm:ss',
    'j': 'HH',
    'jm': 'HH:mm',
    'jms': 'HH:mm:ss',
    'jmv': 'HH:mm v',
    'jmz': 'HH:mm z',
    'jz': 'HH z',
    'm': 'm',
    'ms': 'mm:ss',
    's': 's',
    'v': 'v',
    'z': 'z',
    'zzzz': 'zzzz',
    'ZZZZ': 'ZZZZ',
  };

  static const tkDateSymbols = {
    'NAME': 'tk',
    'ERAS': <dynamic>[
      'f.Kr.',
      'e.Kr.',
    ],
// #enddocregion Date2
    'ERANAMES': <dynamic>[
      'før Kristus',
      'etter Kristus',
    ],
    'NARROWMONTHS': <dynamic>[
      'Ý',
      'F',
      'M',
      'A',
      'M',
      'I',
      'I',
      'A',
      'S',
      'O',
      'N',
      'D',
    ],
    'STANDALONENARROWMONTHS': <dynamic>[
      'Ý',
      'F',
      'M',
      'A',
      'M',
      'I',
      'I',
      'A',
      'S',
      'O',
      'N',
      'D',
    ],
    'MONTHS': <dynamic>[
      'Ýanwar',
      'Fewral',
      'Mart',
      'Aprel',
      'Maý',
      'Iýun',
      'Iýul',
      'Awgust',
      'Dentýabr',
      'Oktýabr',
      'Noýabr',
      'Dekabr',
    ],
    'STANDALONEMONTHS': <dynamic>[
      'Ýanwar',
      'Fewral',
      'Mart',
      'Aprel',
      'Maý',
      'Iýun',
      'Iýul',
      'Awgust',
      'Dentýabr',
      'Oktýabr',
      'Noýabr',
      'Dekabr',
    ],
    'SHORTMONTHS': <dynamic>[
      'ýan.',
      'few.',
      'mart.',
      'apr.',
      'maý.',
      'iýun.',
      'iýul.',
      'awg.',
      'sen.',
      'okt.',
      'noý.',
      'dek.',
    ],
    'STANDALONESHORTMONTHS': <dynamic>[
      'ýan',
      'few',
      'mart',
      'apr',
      'maý',
      'iýun',
      'iýul',
      'awg',
      'sen',
      'okt',
      'noý',
      'dek',
    ],
    'WEEKDAYS': <dynamic>[
      'ýekşenbe',
      'duşenbe',
      'sişenbe',
      'çarşenbe',
      'penşenbe',
      'anna',
      'şenbe',
    ],
    'STANDALONEWEEKDAYS': <dynamic>[
      'ýekşenbe',
      'duşenbe',
      'sişenbe',
      'çarşenbe',
      'penşenbe',
      'anna',
      'şenbe',
    ],
    'SHORTWEEKDAYS': <dynamic>[
      'ýek.',
      'du.',
      'si.',
      'ça.',
      'pe.',
      'an.',
      'şe.',
    ],
    'STANDALONESHORTWEEKDAYS': <dynamic>[
      'ýek',
      'du',
      'si',
      'ça',
      'pe',
      'an',
      'şe',
    ],
    'NARROWWEEKDAYS': <dynamic>[
      'Ý',
      'D',
      'S',
      'Ç',
      'P',
      'A',
      'Ş',
    ],
    'STANDALONENARROWWEEKDAYS': <dynamic>[
      'Ý',
      'D',
      'S',
      'Ç',
      'P',
      'A',
      'Ş',
    ],
    'SHORTQUARTERS': <dynamic>[
      'K1',
      'K2',
      'K3',
      'K4',
    ],
    'QUARTERS': <dynamic>[
      '1. kvartal',
      '2. kvartal',
      '3. kvartal',
      '4. kvartal',
    ],
    'AMPMS': <dynamic>[
      'a.m.',
      'p.m.',
    ],
    'DATEFORMATS': <dynamic>[
      'EEEE d. MMMM y',
      'd. MMMM y',
      'd. MMM y',
      'dd.MM.y',
    ],
    'TIMEFORMATS': <dynamic>[
      'HH:mm:ss zzzz',
      'HH:mm:ss z',
      'HH:mm:ss',
      'HH:mm',
    ],
    'AVAILABLEFORMATS': null,
    'FIRSTDAYOFWEEK': 1,
    'WEEKENDRANGE': <dynamic>[
      6,
      7,
    ],
    'FIRSTWEEKCUTOFFDAY': 3,
    'DATETIMEFORMATS': <dynamic>[
      '{1} {0}',
      '{1} \'kl\'. {0}',
      '{1}, {0}',
      '{1}, {0}',
    ],
  };
}
